# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a0d78c4f40fc2e70c60b0a0616cf90f63a7a3ca01df365953071f10edb8ee23f6b5b2cb0dff50bbe2c6a9df5c60a7edeff5aba33ba2aff1c6c08a21d487a87f

test:
  secret_key_base: 3dc946b9c9b9b2bc2802d9d6f51f55f0f59bdf3069f4612228306eea9281ac859f2d2bef9dfe4dd6fca85914d0b97a08d2e3405254831b5b64e7084d32939aef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
